# Config file for automatic testing at travis-ci.org
sudo: false
dist: trusty

language: python
python:
  - "3.5"

env:
  - TOXENV=py35-django-111
  - TOXENV=py34-django-111
  - TOXENV=py27-django-111
  - TOXENV=py35-django-2
  - TOXENV=py34-django-2
  # tox py 36 with py3.5 installed does not play nicely on travis
  # and tox python 3.5 with travis pythong 3.6 as the root also
  # does not play nicely, so
  #- TOX_ENV=py36-django-111

matrix:
  fast_finish: true
  include:
    # - python: '2.7'
    #   env: TOX_ENV=py27-django-19
    # - python: '3.4'
    #   env: TOX_ENV=py34-django-19
    # - python: '3.5'
    #   env: TOX_ENV=py35-django-19
    # - python: '2.7'
    #   env: TOX_ENV=py27-django-110
    # - python: '3.4'
    #   env: TOX_ENV=py34-django-110
    # - python: '3.5'
    #   env: TOX_ENV=py35-django-110
    # - python: '2.7'
    #   env: TOX_ENV=py27-django-111
    # - python: '3.4'
    #   env: TOX_ENV=py34-django-111
    # - python: '3.5'
    #   env: TOX_ENV=py35-django-111
    - python: '3.6'
      env:
        - TOXENV=py36-django-111
        - TOXENV=py36-django-2

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U pip
  - pip install -r requirements_test.txt
  - pip install tox

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
